"use client";

import { FileText, Download, Search, Filter, Calendar } from "lucide-react";
import { cn } from "@/lib/utils";
import { useState } from "react";
import Pagination from "@/components/Pagination";

const allReports = [
    { name: "Daily Weighbridge Summary", category: "Operational", created: "2024-03-24", author: "System", size: "1.2 MB", format: "PDF" },
    { name: "Shift Performance Report", category: "Performance", created: "2024-03-24", author: "System", size: "850 KB", format: "XLSX" },
    { name: "Stockpile Reconciliation", category: "Inventory", created: "2024-03-23", author: "John Doe", size: "2.4 MB", format: "PDF" },
    { name: "Transporter Efficiency", category: "Logistics", created: "2024-03-23", author: "System", size: "1.8 MB", format: "XLSX" },
    { name: "Vessel Loading Manifest", category: "Operational", created: "2024-03-22", author: "Sarah Smith", size: "3.1 MB", format: "PDF" },
    { name: "Visitor Access Log", category: "Security", created: "2024-03-22", author: "System", size: "500 KB", format: "CSV" },
    { name: "Environmental Compliance", category: "Compliance", created: "2024-03-21", author: "Mike Brown", size: "4.2 MB", format: "PDF" },
    { name: "Monthly Financial Summary", category: "Financial", created: "2024-03-01", author: "Finance Dept", size: "5.5 MB", format: "PDF" },
];

export default function AllReportsPage() {
    const [currentPage, setCurrentPage] = useState(1);
    const [itemsPerPage, setItemsPerPage] = useState(25);

    const totalItems = allReports.length;
    const totalPages = Math.ceil(totalItems / itemsPerPage);
    const startIndex = (currentPage - 1) * itemsPerPage;
    const endIndex = startIndex + itemsPerPage;
    const paginatedReports = allReports.slice(startIndex, endIndex);

    return (
        <div className="space-y-6">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div>
                    <h1 className="text-3xl font-bold text-slate-900">All Reports</h1>
                    <p className="text-slate-500">Archive of all generated system reports</p>
                </div>
                <div className="flex gap-2">
                    <button className="flex items-center px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700 transition shadow-lg shadow-blue-500/20">
                        Generate New Report
                    </button>
                </div>
            </div>

            <div className="flex flex-col md:flex-row gap-4 bg-white p-4 rounded-xl border border-slate-200 shadow-sm">
                <div className="relative flex-1">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                    <input
                        type="text"
                        placeholder="Search reports by name..."
                        className="w-full pl-10 pr-4 py-2 bg-slate-50 border border-slate-200 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none transition-all"
                    />
                </div>
                <div className="flex gap-2">
                    <button className="flex items-center px-4 py-2 bg-white border border-slate-200 rounded-lg text-sm font-medium hover:bg-slate-50 transition text-slate-700">
                        <Filter className="w-4 h-4 mr-2" />
                        Category
                    </button>
                    <button className="flex items-center px-4 py-2 bg-white border border-slate-200 rounded-lg text-sm font-medium hover:bg-slate-50 transition text-slate-700">
                        <Calendar className="w-4 h-4 mr-2" />
                        Date Range
                    </button>
                </div>
            </div>

            <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
                <table className="w-full text-left">
                    <thead className="bg-slate-50 text-xs uppercase text-slate-500 font-semibold">
                        <tr>
                            <th className="px-6 py-4">Report Name</th>
                            <th className="px-6 py-4">Category</th>
                            <th className="px-6 py-4">Date Created</th>
                            <th className="px-6 py-4">Generated By</th>
                            <th className="px-6 py-4">Size</th>
                            <th className="px-6 py-4 text-center">Action</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                        {paginatedReports.map((report, i) => (
                            <tr key={i} className="hover:bg-slate-50/50 transition-colors">
                                <td className="px-6 py-4">
                                    <div className="flex items-center gap-3">
                                        <div className="p-2 bg-blue-50 text-blue-600 rounded-lg">
                                            <FileText className="w-4 h-4" />
                                        </div>
                                        <span className="font-medium text-slate-900">{report.name}</span>
                                    </div>
                                </td>
                                <td className="px-6 py-4">
                                    <span className="px-2 py-1 bg-slate-100 text-slate-600 text-xs font-medium rounded-full border border-slate-200">
                                        {report.category}
                                    </span>
                                </td>
                                <td className="px-6 py-4 text-slate-500 text-sm">{report.created}</td>
                                <td className="px-6 py-4 text-slate-600 text-sm">{report.author}</td>
                                <td className="px-6 py-4 text-slate-500 text-sm font-mono">{report.size}</td>
                                <td className="px-6 py-4 text-center">
                                    <button className="text-blue-600 hover:text-blue-800 transition p-2 hover:bg-blue-50 rounded-lg">
                                        <Download className="w-4 h-4" />
                                    </button>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            {allReports.length > 0 && (
                <Pagination
                    currentPage={currentPage}
                    totalPages={totalPages}
                    itemsPerPage={itemsPerPage}
                    totalItems={totalItems}
                    onPageChange={setCurrentPage}
                    onItemsPerPageChange={(newItemsPerPage) => {
                        setItemsPerPage(newItemsPerPage);
                        setCurrentPage(1);
                    }}
                    itemsPerPageOptions={[10, 25, 50, 100]}
                />
            )}
        </div>
    );
}
